name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Check formatting and linting
        run: |
          pnpm run check

  test:
    needs: check
    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Run gauge ts unit tests
        run: |
          pnpm --filter gauge-ts test
        env:
          CI: true

  build-artifacts:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true
          cache: pnpm

      - name: Create artifact
        run: |
          pnpm install --frozen-lockfile
          pnpm --filter gauge-ts run package
          pnpm --filter gauge-ts pack --out ./gauge-ts/artifacts/gauge-ts-npm.tgz

      - name: Upload artifacts for local
        uses: actions/upload-artifact@v6
        with:
          name: gauge-ts
          path: ./gauge-ts/artifacts

  e2e-test:
    needs: build-artifacts
    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [macOS-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - uses: actions/download-artifact@v7
        with:
          name: gauge-ts
          path: ./artifacts

      - name: Install gauge-ts
        run: |
          cd e2e
          pnpm exec gauge install ts -f ../artifacts/gauge-ts-*.zip
        shell: bash

      - name: Type check the e2e project
        run: |
          pnpm --filter e2e run typecheck

      - name: Run functional tests
        run: |
          pnpm --filter e2e run test
        shell: bash
